Feature
Emmanuelaaron/News-week-clone pull request #5
Opened 2020-04-13 12:26 UTC by Emmanuelaaron

**Using Bootstrap - Solo project:** 

In this project, I built a clone of The [Newsweek](https://www.newsweek.com/) home page using bootstrap 

Following are some specifications of our project: 
- breaking points at (mobile view)320px,  (tablet view)768px and (Large screen)1440px;

2020-04-13 12:53 UTC, majovanilla commented
# Code Review in progress 👀 by Maria Reyes

2020-04-13 13:34 UTC, majovanilla requested changes
Het @Emmanuelaaron !!

## You did a *great* job on this project! 💜 


- Good Readme file
- Good Pull Request Message

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Your page has a different gutter size (the space between columns) and a different margin size on the edges. That makes your elements stick to the sides of the window when you make it smaller and that shouldn't happen. Please fix this.
![Screenshot from 2020-04-13 08-24-05](https://user-images.githubusercontent.com/51926937/79123616-2cca2880-7d60-11ea-845a-179b1d75251f.png)

- Check my review on the commented code below.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Use semantic HTML in the structure of your HTML file. Favor the use of `<nav>`,  `<article>`,   to enclose the elements on your file. 

- Your project would look sooo much better if you include the hover effects on the links of the page, like the original version.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-13 13:34 UTC, majovanilla commented on README.md
> +
- Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...Check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more info.

2020-04-13 13:34 UTC, majovanilla commented on styles/responsive.css
> +}
Remember the purpose of the project is to use Bootstrap. Please favor the use of bootstrap classes in this case.

2020-04-13 13:34 UTC, majovanilla commented on styles/responsive.css
> +
Remember the purpose of the project is to use Bootstrap. Please favor the use of bootstrap classes in this case.

2020-04-13 13:34 UTC, majovanilla commented on styles/responsive.css
> +  }
Remember the purpose of the project is to use Bootstrap. Please favor the use of bootstrap classes in this case.

2020-04-13 13:34 UTC, majovanilla commented on styles/responsive.css
> +    width: 100%;
Remember the purpose of the project is to use Bootstrap. Please favor the use of bootstrap classes in this case.

2020-04-13 13:34 UTC, majovanilla commented on styles/style.css
> +}
Remember the purpose of the project is to use Bootstrap. Please favor the use of bootstrap classes in this case.

2020-04-13 13:34 UTC, majovanilla commented on styles/style.css
> +}
Remember the purpose of the project is to use Bootstrap. Please favor the use of bootstrap classes in this case.

2020-04-13 13:34 UTC, majovanilla commented on styles/style.css
> +}
Remember the purpose of the project is to use Bootstrap. Please favor the use of bootstrap classes in this case.

2020-04-13 13:34 UTC, majovanilla commented on styles/style.css
> +}
Remember the purpose of the project is to use Bootstrap. Please favor the use of bootstrap classes in this case.

2020-04-13 13:34 UTC, majovanilla commented on styles/style.css
> +}
Remember the purpose of the project is to use Bootstrap. Please favor the use of bootstrap classes in this case.

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +    <input type="text" placeholder="Search" class="col-lg-1 search-input mt-lg-2">
Use semantic HTML. In this case, you can change the div that contains your list and change it for a `<nav>` tag

Please check the size and spacing of your `<li>` elements. The original page has a different look (font-size, less padding...)
Yours:
![Screenshot from 2020-04-13 08-01-22](https://user-images.githubusercontent.com/51926937/79122523-7bc28e80-7d5d-11ea-88ca-065a83d9670e.png)

Original:
![Screenshot from 2020-04-13 08-05-12](https://user-images.githubusercontent.com/51926937/79122540-85e48d00-7d5d-11ea-8eab-5abcc629d052.png)

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +          <h2>opinion</h2>
Check the looks of this section. Yours has more spacing between elements.
Yours:
![Screenshot from 2020-04-13 08-01-27](https://user-images.githubusercontent.com/51926937/79122484-5e8dc000-7d5d-11ea-88cf-bf2f731b93f7.png)

Original:
![Screenshot from 2020-04-13 08-01-33](https://user-images.githubusercontent.com/51926937/79122494-62b9dd80-7d5d-11ea-94c9-6ea9a0d3d036.png)

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +                <img
Check this section. Your font-size is not the same and the font colors also need some work.
Check the badges on the images, too and add them.
On mobile screens, your  section has no title.

Yours:
![Screenshot from 2020-04-13 08-06-42](https://user-images.githubusercontent.com/51926937/79122645-d956db00-7d5d-11ea-8530-ae9e6aeaf9ea.png)

Original:
![Screenshot from 2020-04-13 08-06-49](https://user-images.githubusercontent.com/51926937/79122653-dd82f880-7d5d-11ea-985a-8023d7d29acc.png)

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +          <div>
The images on this section and the Featured stories should have a white badge with red text on the bottom-left corner. Please add them.

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +              <img
Check the spacing on this section. Your articles are more separated than the original page.

On mobile screens, your section has no title and it looks disorganized.
![Screenshot from 2020-04-13 08-30-51](https://user-images.githubusercontent.com/51926937/79124078-2ee0b700-7d61-11ea-8b00-adaf592885bf.png)

Original:
![Screenshot from 2020-04-13 08-30-45](https://user-images.githubusercontent.com/51926937/79124085-330cd480-7d61-11ea-90c2-a59701a0ba3c.png)

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +                <img
Check the spacing on this section. Your articles are more separated than the original page.

On medium screens, your images lose the proper sizing.
![Screenshot from 2020-04-13 08-29-50](https://user-images.githubusercontent.com/51926937/79124183-62bbdc80-7d61-11ea-9893-f5a0cad6ccb3.png)

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +          alt="" class="w-100">
The first image of this section should be taller than the rest of the images. Please fix this,

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +      </div>
The size of the articles in this section is not the same as the original page. Please make them look like a clone. Check everything: sizing, fonts, spacing, etc. 
Yours:
![Screenshot from 2020-04-13 08-14-24](https://user-images.githubusercontent.com/51926937/79123037-d27c9800-7d5e-11ea-8ec9-6c17cc759277.png)

Orginal:
![Screenshot from 2020-04-13 08-14-30](https://user-images.githubusercontent.com/51926937/79123044-d6101f00-7d5e-11ea-8eb9-bef774d4213c.png)

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +        <img
Check the spacing on your categories'  sections. You have a lot of space after each one and before the division border. Try to make them look like the original page.
Yours:
![Screenshot from 2020-04-13 08-16-49](https://user-images.githubusercontent.com/51926937/79123228-4c148600-7d5f-11ea-87b5-236af34f61bb.png)

Orginal:
![Screenshot from 2020-04-13 08-16-39](https://user-images.githubusercontent.com/51926937/79123235-4fa80d00-7d5f-11ea-845a-11ea851d67e0.png)

On medium screens, the elements on the right look cramped (no spacing between images and text) and the font-size is larger on the main articles.
![Screenshot from 2020-04-13 08-27-38](https://user-images.githubusercontent.com/51926937/79123889-c2fe4e80-7d60-11ea-91b0-c261dc8d8fd7.png)

On mobile screens, the three articles on the bottom should occupy 100% width.
![Screenshot from 2020-04-13 08-27-20](https://user-images.githubusercontent.com/51926937/79123918-d5788800-7d60-11ea-8194-e67f712a1c12.png)

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +      </section>
Your subscribe and newsletter sections need some work: 
- Check the titles, they should be aligned left.
- Check the spacing between them, they should be closer.
- Check the Subscribe background-color: it's different.
- Add the two images to the subscribe section.

Yours:
![Screenshot from 2020-04-13 08-18-43](https://user-images.githubusercontent.com/51926937/79123424-bf1dfc80-7d5f-11ea-98fe-0320be9037d3.png)

Original:
![Screenshot from 2020-04-13 08-18-49](https://user-images.githubusercontent.com/51926937/79123430-c6450a80-7d5f-11ea-94c3-19fad988bbbc.png)

The mobile version is not working correctly. Your Subscribe has a very large image that shouldn't have that size, and the newsletter looks like this:
![Screenshot from 2020-04-13 08-25-37](https://user-images.githubusercontent.com/51926937/79123729-68fd8900-7d60-11ea-97f6-d0c9d68bd6d4.png)

2020-04-13 13:34 UTC, majovanilla commented on index.html
> +          <li class="ml-1 text-center">Consent preferences</li>
Check the font color of these elements and make them look like the original page.
When you are on medium and mobile sizes., your footer elements should be aligned left.

2020-04-13 18:31 UTC, uryelah commented
Hello **Isabirye Isabirye**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all the scroll at top sections of the clone on wide screens is looking great. You really nailed down the hardest parts of this project 🌟**

I see that you fulfilled most of the requests from the last TSE but you'll need to revisit some you missed before moving on. Hang in there 💪

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] Make your navbar fixed like in the [original site](https://www.newsweek.com/).

- [ ] The 'Subscribe' section should have two magazine page images like the original one. Compare your version and the original below:
 ![Screenshot_2020-04-13 Newsweek](https://user-images.githubusercontent.com/16193212/79147070-c235de80-7d99-11ea-8771-c8cdc8d2482f.png)
![Screenshot_2020-04-13 Newsweek(1)](https://user-images.githubusercontent.com/16193212/79147072-c2ce7500-7d99-11ea-9a29-5c2ed13040d8.png)

-----

- [ ] Something is leaking from your navbar on wide screens. Make sure to fix the extra red area. 
- [ ] Also add the weather information on the navbar. Remember, you are required to make an extra close clone for this project.
**Your version:**
![Screenshot_2020-04-13 Newsweek(2)](https://user-images.githubusercontent.com/16193212/79147302-1c36a400-7d9a-11ea-8995-bffd3d7fe75c.png)
**Original version:**
![Screenshot_2020-04-13 Newsweek(3)](https://user-images.githubusercontent.com/16193212/79147300-1b9e0d80-7d9a-11ea-9840-fed709f0dafb.png)

------

- [ ] Remember to add the topic over the image for the 'Featured Stories' articles and to add some margin under the image or above the title:
**Your version:**
![Screenshot_2020-04-13 Newsweek(5)](https://user-images.githubusercontent.com/16193212/79147461-5738d780-7d9a-11ea-8d74-cf669fcd98ae.png)
**Original version:**
![Screenshot_2020-04-13 Newsweek(4)](https://user-images.githubusercontent.com/16193212/79147463-57d16e00-7d9a-11ea-928a-33b95fbcf475.png)
 
-----

- [ ] Pay attention to font family, color, size, and weight. Change your version so it's closer to the original:
**Your version:**
![Screenshot_2020-04-13 Newsweek(7)](https://user-images.githubusercontent.com/16193212/79147669-af6fd980-7d9a-11ea-8b51-599519eeb263.png)
**Original version:**
![Screenshot_2020-04-13 Newsweek(6)](https://user-images.githubusercontent.com/16193212/79147674-b0a10680-7d9a-11ea-9ff2-8ff70b9ff3bc.png)

----

**Your version:**
![Screenshot_2020-04-13 Newsweek(9)](https://user-images.githubusercontent.com/16193212/79147673-b0a10680-7d9a-11ea-8cc0-5ea2eb69e07b.png)
**Original version:**
![Screenshot_2020-04-13 Newsweek(8)](https://user-images.githubusercontent.com/16193212/79147670-b0087000-7d9a-11ea-9732-a230b934b6e7.png)


-----

- [ ] Like my colleague observed before, make sure the margin between sections is not too wide. Compare the space between sections in your clone and in the original version:
![Screenshot_2020-04-13 Newsweek(11)](https://user-images.githubusercontent.com/16193212/79147926-1f7e5f80-7d9b-11ea-9a56-478f8ddf1811.png)
![Screenshot_2020-04-13 Newsweek(10)](https://user-images.githubusercontent.com/16193212/79147927-2016f600-7d9b-11ea-9cf3-9f6ac9877cbc.png)


------

- [ ] Make sure the side images from the topics sections don't change width on resize:
![Screenshot_2020-04-13 Newsweek(12)](https://user-images.githubusercontent.com/16193212/79148319-ad5a4a80-7d9b-11ea-9247-99af5d8ed01b.png)
![Screenshot_2020-04-13 Newsweek(13)](https://user-images.githubusercontent.com/16193212/79148322-adf2e100-7d9b-11ea-9d15-ced37c6b1ae9.png)

-----

- [ ] Make sure the bottom sections and footer follow the original page style on medium and small break points:
![Screenshot_2020-04-13 Newsweek(15)](https://user-images.githubusercontent.com/16193212/79148336-b2b79500-7d9b-11ea-8142-eb1e841924de.png)
![Screenshot_2020-04-13 Newsweek(14)](https://user-images.githubusercontent.com/16193212/79148340-b3502b80-7d9b-11ea-9e77-f217ca77d502.png)


-----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-04-13 23:02 UTC, thsvr commented
### **STATUS: CHANGES REQUESTED** :bulb: :bulb: 

Hi @Emmanuelaaron :smile: :smile: 
### 
**You are doing a great job and you are almost there** :muscle: 

I notice that you implemented some of the requested changes Sarah(TSE) asked you to do :fireworks: but to have this project approved, you need to do all the requested changes. I listed them below, can you please read it carefully, do the changes and then ask for another code review? :smile_cat: 

:bug: As asked by Sarah, you need to _"Make your navbar fixed like in the original site"_. Can you please fix it?

:bug: As asked by Sarah, _"The 'Subscribe' section should have two magazine page images like the original one. Compare your version and the original"_ and please change the size of the magazine on the top. 

:bug: As asked by Sarah, you _"Also add the weather information on the navbar."_ Can you please fix it? 

:bug: As mentioned by Sarah, can you _"Make sure the side images from the topics sections don't change the width on resizing."_ and please fix it?

:bug: As mentioned by Sarah, _"Make sure the bottom sections and footer follow the original page style on medium and small breakpoints:"_ , so I notice they are not similar as the original, for example, on the footer you need to add some margin/padding to it looks close to the original. can you please fix it? 


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)

### **Happy coding and good luck on the next review** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

2020-04-14 23:44 UTC, christianotieno commented
## Pull Request under review by Christian Otieno (TSE)

2020-04-15 00:13 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @Emmanuelaaron  :wave:
-
Good job implementing the changes! :tada: Keep it up.
We, however, do have some few changes to carry out before we close this (see review comment).
##
## [REQUIRED] - FIX - The navbar during breakpoints. 
- During screen breaks at (1037 X 378), the navbar breaks. This is our current status: 👇
![(1037 X 378)screen_clone](https://user-images.githubusercontent.com/22345961/79285164-6a949180-7ec5-11ea-872a-ed2613756260.png)
 This is what we should be having at that breakpoint 👇 
![header](https://user-images.githubusercontent.com/22345961/79285206-8f890480-7ec5-11ea-864c-7419f30edf54.png)
- Also, remove the hover effect on the signup links and increase the fonts on the links (Sign in and subscribe) as well. Thanks 

## [REQUIRED] - FIX  - The opinion section
- In our opinion section we have some unwanted spaces between elements: 👇 
![opnion_clone](https://user-images.githubusercontent.com/22345961/79285222-9fa0e400-7ec5-11ea-83f7-7836b9abbe43.png)
- Let's aim for this compact form👇 
![opinion](https://user-images.githubusercontent.com/22345961/79285279-c4955700-7ec5-11ea-94bc-53724d27dc54.png)

## [REQUIRED] - FIX - The signup newsletter section
- let's get rid of the unnecessary spacings and increase the colour contrast in this section.
![signup_clone](https://user-images.githubusercontent.com/22345961/79285411-2d7ccf00-7ec6-11ea-9bd4-f7a7c508a6f8.png)
- We are aiming to achieve this: 👇 
![signup](https://user-images.githubusercontent.com/22345961/79285523-7df42c80-7ec6-11ea-8e5e-c257ef8e7a71.png)

## [REQUIRED] - FIX - The small screen header
- One final change we have to perform is the header at the small screen: 👇 
![small_screen_header_clone](https://user-images.githubusercontent.com/22345961/79285588-abd97100-7ec6-11ea-8676-e354647df846.png)

- Let's shape things up to mat its sister: 👇 
![small_screen](https://user-images.githubusercontent.com/22345961/79285609-be53aa80-7ec6-11ea-8bc1-4901c10ac609.png)

That should be all.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-04-15 18:27 UTC, uryelah commented
Hey there, great job with the fixes. I can see you did great progress since the first code review. 
There are still some issues with the responsiveness of the page, especially in small screens.

I highly recommend you to use your browser of choice developer tools for changing the screen width while developing and making sure the layout never breaks. [Check this video for a demonstration on how to use Firefox responsive design tools.](https://youtu.be/qGI27bpCZK4)

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] The 'More stories' section is overlapping its text and images on resizing at small screens. Check it bellow how it looks in your clone and how it looks in the original:
![Screenshot_2020-04-15 Newsweek(5)](https://user-images.githubusercontent.com/16193212/79373548-1cb37400-7f2d-11ea-9bb3-d2bf6d99cc81.png)
**Original page:**
![Screenshot_2020-04-15 Newsweek(6)](https://user-images.githubusercontent.com/16193212/79373552-1de4a100-7f2d-11ea-81bf-a4de1459784a.png)


----

- [ ] Something similar is happening at the 'Subscribe' section:
![Screenshot_2020-04-15 Newsweek(3)](https://user-images.githubusercontent.com/16193212/79373644-3a80d900-7f2d-11ea-8021-353a4ec06663.png)
**Original PageL**
![Screenshot_2020-04-15 Newsweek(4)](https://user-images.githubusercontent.com/16193212/79373645-3bb20600-7f2d-11ea-9d7c-d3eded768a39.png)


-----

- [ ] Make The footer icons and text are justified and aligned like the original on small screens:
![Screenshot_2020-04-15 Newsweek(2)](https://user-images.githubusercontent.com/16193212/79373728-51273000-7f2d-11ea-8b30-0f544dcafc32.png)
**Original page:**
![Screenshot_2020-04-15 Newsweek(1)](https://user-images.githubusercontent.com/16193212/79373735-51bfc680-7f2d-11ea-8cb6-e3abc577532f.png)

------

You are doing really great, responsiveness can take a lot of work, but when you are done and have a solid and reliable site on your hands you'll be ready to tackle amazing professional-looking projects.

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-04-16 23:46 UTC, rOluochKe requested changes
Hello @Emmanuelaaron 
### good job so far :clap: and for also making changes from previous reviews. However, you have a few issues to solve before your project could be approved. You are close.
- Your images are not responsive on mobile devices, they need to be proportional
![image not proportional](https://user-images.githubusercontent.com/8114528/79516687-bc1f5680-8054-11ea-9441-bd6acc053a93.png)
- On mobile devices, the width of the content (image and text to go full width), refer original design
![on mobile full width](https://user-images.githubusercontent.com/8114528/79516738-e2dd8d00-8054-11ea-80f9-69899227ec58.png)
- On mobile make the image and text align with the rest of the content
![out of place on mobile](https://user-images.githubusercontent.com/8114528/79516778-06a0d300-8055-11ea-8a7e-2ce6e29c1bef.png)
- On mobile devices, image thumbnail is aligned to the left and text to the right, refer original design
![on mobile text are aligned to the right](https://user-images.githubusercontent.com/8114528/79517064-c857e380-8055-11ea-9c3c-e3f0c20cc598.png)
- Your footer is not designed properly, the background of the subscribe section overlaps both for large, medium and mobile devices
![subscribe footer section](https://user-images.githubusercontent.com/8114528/79516905-66977980-8055-11ea-9b6f-2409d8e67dc1.png)
- Also, solve issues raised by stickler on CSS

### Put more work on the responsiveness of your application

### make these changes and resubmit for another code review. good luck
- For clarity, contact me on slack @iamraymond
- happy coding!

2020-04-17 07:53 UTC, lekegitrepo commented
### @Emmanuelaaron 👏 👏
### Good job for the implementation of the required changes mentioned in the previous review. You are almost there 💪
#### Try to fix 👇
**_1. The subscribe and newsletter: they should be of the same height and you can also reduce the width of the subscribe content a little bit and increase the width of the newsletter content a little bit_**

**_2. The images are missing in the "latest news" section._**

**_kindly make the changes and submit for review._**

**_if you have any doubts or questions contact me on slack._**

### _Reviewed by Temitayo Adeleke_

2020-04-17 07:54 UTC, lekegitrepo requested changes
#### Status: Request changes

2020-04-17 22:42 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-04-17 22:49 UTC, addod19 approved these changes
## Status: Approved 🏆 🎈 

Hi @Emmanuelaaron, congratulations on fixing all the changes recommended by the previous TSE's 👍 Thanks to the reviews and your hard work, the project has now met all the minimum requirements 😄 

[OPTIONAL] 
- Kindly add your email to the author section of the README file

Go ahead and merge to master, do not forget to submit the project completion form 🙂 
_Happy coding_ 👨‍💻 
Good luck with your next projects 😃 
Daniel Larbi Addo on slack

2020-04-17 23:32 UTC, merged